name: CI/CD - Restaurant Management API

on:
  push:
    branches: [ main, develop, feature/add-cloud-run-iac ]
  pull_request:
    branches: [ main, develop ]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Verificar branches conflitantes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔑 Configurar credenciais do Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 🔍 Testar merge main <- develop
        run: |
          git fetch origin
          git checkout main
          git merge --no-commit --no-ff origin/develop || (
            echo "❌ Conflitos detectados entre main e develop" && exit 1
          )
          git merge --abort || true
          echo "✅ Nenhum conflito entre main e develop"

  check:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: ✅ Checar padrão de código
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: ✅ Rodar testes
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🚀 Build do projeto
        run: npm run build

      - name: ⬆️ Upload dos artefatos de build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_SERVICE_NAME: api-restaurant

    permissions:
      contents: read
      id-token: write

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🔐 Autenticar com o Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER}}

      - name: ⬇️ Download dos artefatos de build
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: ☁️ Deploy no Cloud Run (Staging)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_SERVICE_NAME }}
          suffix: stg
          region: us-east1
          source: dist/

      - name: ☁️ Deploy no Cloud Run (Production)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCP_SERVICE_NAME }}
          suffix: prd
          region: southamerica-east1
          source: dist/
